# Generated by Django 4.1.3 on 2022-11-20 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'شهر ',
                'verbose_name_plural': 'شهر ها',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='سن')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'کاربر عادی ',
                'verbose_name_plural': 'کاربران عادی',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی')),
                ('gmc_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره نظام پزشکی')),
                ('gender', models.CharField(choices=[('زن', 'female'), ('مرد', 'male')], default='male', max_length=6, verbose_name='جنسیت')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='سن')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'پزشک  ',
                'verbose_name_plural': 'پزشکان ',
            },
        ),
    ]
