# Generated by Django 4.1.3 on 2022-11-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(choices=[('زن', 'female'), ('مرد', 'male'), ('دیگر', 'others')], default='male', max_length=6, verbose_name='جنسیت'),
        ),
    ]
