# Generated by Django 4.1.3 on 2022-12-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver_id',
        ),
    ]
