# Generated by Django 4.1.3 on 2022-12-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_national_code_alter_city_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'زن'), ('male', 'مرد'), ('others', 'دیگر')], default='male', max_length=6, verbose_name='جنسیت'),
        ),
    ]
