# Generated by Django 4.1.3 on 2022-11-22 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bookingsettings_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'نوبت', 'verbose_name_plural': ' نوبت ها'},
        ),
        migrations.AlterModelOptions(
            name='bookingsettings',
            options={'verbose_name': 'تنظیم نوبت دکتر', 'verbose_name_plural': ' تنظیمات نوبت دکتر ها'},
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.doctorprofile', verbose_name='پزشک'),
        ),
    ]
