# Generated by Django 4.1.3 on 2022-12-28 14:32

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_message_text_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_expertise_name', models.CharField(max_length=50, unique=True, verbose_name='نام تخصص')),
            ],
            options={
                'verbose_name': 'شهر ',
                'verbose_name_plural': 'شهر ها',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medical_expertise',
            field=models.ForeignKey(blank=True, default=api.models.MedicalExpertise.get_default_pk, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.medicalexpertise', verbose_name='تخصص'),
        ),
    ]
