# Generated by Django 4.1.3 on 2022-11-22 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_booking_options_alter_bookingsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.doctorprofile', verbose_name='پزشک'),
        ),
    ]
