# Generated by Django 4.1.3 on 2023-01-03 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_medicalexpertise_userprofile_medical_expertise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalexpertise',
            options={'verbose_name': 'تخصص ', 'verbose_name_plural': 'تخصص ها'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_user', to='api.userprofile', verbose_name='پزشک'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normal_user', to='api.userprofile', verbose_name='بیمار'),
        ),
    ]
