# Generated by Django 4.1.3 on 2022-11-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_booking_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_mobile',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='approved',
            field=models.BooleanField(default=True, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(verbose_name='ساعت'),
        ),
    ]
