# Generated by Django 4.1.3 on 2023-01-22 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_medicalexpertise_options_alter_booking_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_input', models.CharField(max_length=200, verbose_name='ورودی تست')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'تست پزشکی',
                'verbose_name_plural': ' تست های پزشکی',
            },
        ),
    ]
