# Generated by Django 4.1.3 on 2023-01-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_medicaltest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_response', models.CharField(max_length=100, verbose_name='بیماری')),
                ('test_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.medicaltest', verbose_name='تست')),
            ],
            options={
                'verbose_name': 'پاسخ تست  ',
                'verbose_name_plural': 'پاسخ های تست ',
            },
        ),
    ]
