# Generated by Django 4.1.3 on 2022-11-22 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_remove_booking_user_email_remove_booking_user_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingsettings',
            name='available_booking_months',
        ),
        migrations.RemoveField(
            model_name='bookingsettings',
            name='booking_enable',
        ),
        migrations.RemoveField(
            model_name='bookingsettings',
            name='confirmation_required',
        ),
        migrations.RemoveField(
            model_name='bookingsettings',
            name='disable_weekend',
        ),
        migrations.RemoveField(
            model_name='bookingsettings',
            name='max_booking_per_time',
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='بیمار'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='end_time',
            field=models.TimeField(verbose_name='ساعت پایان کار'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='max_booking_per_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='حداکثر بیمار در روز'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='period_of_each_booking',
            field=models.CharField(choices=[('5', '5M'), ('10', '10M'), ('15', '15M'), ('20', '20M'), ('25', '25M'), ('30', '30M'), ('35', '35M'), ('40', '40M'), ('45', '45M'), ('60', '1H'), ('75', '1H 15M'), ('90', '1H 30M'), ('105', '1H 45M'), ('120', '2H'), ('150', '2H 30M'), ('180', '3H')], default='30', max_length=3, verbose_name='زمان هر نوبت'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='start_time',
            field=models.TimeField(verbose_name='ساعت شروع کار'),
        ),
    ]
