# Generated by Django 4.1.3 on 2023-01-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_medicaltest_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر ')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'پست آموزشی   ',
                'verbose_name_plural': ' پست های آموزشی ',
            },
        ),
    ]
