# Generated by Django 4.1.3 on 2023-01-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_image',
        ),
    ]
