# Generated by Django 4.1.3 on 2023-01-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_blogpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
    ]
